### PR TITLE
Placeholder fixes

### PR DESCRIPTION
**Pull request by Hemaolle**
This happened if text was first entered and then deleted. Fix by displaying only the Unity placeholder.

Also hide/display the placeholder on change of focus instead of when the user starts typing or empties the field.

### CODE REVIEW

**Comment by Nezz** [comment]
>Currently we are using the Unity placeholder, which only gets hidden when the user starts typing (not on focus).
Note that this isn't the out of the box behaviour of Unity, we built it to act like this ourselves. Would be nice to add an option to disable the placeholder completely

**Comment by Hemaolle** [comment]
Do you mean that we should have a setting to disable the placeholder on focus? That seems to be the default Unity behaviour and yeah, it would make sense to make it like work like that by default.

Disabling the placeholder completely already works the same way as it used to, you can either remove the placeholder text or disable the GameObject

**Comment by Hemaolle** [comment]
All right, now the NativeEditBox should work exactly like the Unity InputField. We can implement the "hide only when the user starts typing" behaviour separately from the NativeEditBox.

Btw, a multiline NativeEditBox seems to run quite a lot of code not run by a single line one. Do you think we should test that too now or maybe leave it for now and come back if we need it in the future? Of course if we want to publish this, I guess it would be nice to have that too working :smile:

**Comment by Nezz** [comment]
Looks good now :) I'd leave the multiline for later.

**Pull request merged**
