### PR TITLE
Disable on Android for unity 5.6

### PR DESCRIPTION
**Pull request by sbergen**

### CODE REVIEW

**Comment by Nezz** [comment]
Is this really happening? I hope not :/

**Comment by Hemaolle** [comment]
Yeah, there was apparently some issue with the splash screen with the `UnityPlayerOnTop` fix so the guys made the call to pull it. I can start working on a workaround for that if you like, @Nezz. Or we could try a different approach where the NativeInputField is in a different window on top of the Unity window. Not working on it right now, but let me know if you think we should do it.

**Comment by Hemaolle** [comment]
Not sure if there was some other issue related to the NativeInputFields. I heard some mention about the Youtube backing tracks but not sure about the conclusion on that.

**Comment by sbergen** [comment]
@Nezz The plugin is implemented in a way that
* "Was never guaranteed to work with Unity", and will not be "fixed" by Unity (this is from a Unity employee in the forum, and in multiple bug reports)
* Broke in Unity 5.6
* Messes with the Browser plugin we use for YouTube, causing crashes

We tried to work around it, but the splash screen disappeared, courtesy of the workaround, and it would still cause crashes. It's simply really badly implemented on Android, and will need some radical changes to it if we want to re-enable it.

**Comment by Hemaolle** [comment]
I'm not sure if we should merge this to master BTW, because it would disable the plugin on Android also for people using it on older Unity versions. I suggest we just keep it as a branch.

It would be good to make a Github issue for the problem we had so that other users of the plugin would know about it.

**Comment by Nezz** [comment]
If you disable it it will ruin the sign up experience. Try it for yourself :/

**Comment by sbergen** [comment]
@Nezz we should still improve the signup experience from what it is after disabling, and think we should still hotfix that... We unfortunately did have to rush a bit on Friday, due to Joonas going on holidays and not yet having had the chance to walk others through the release process.

However, getting the videos to play on Android on bad internet connections (fixed in Unity 5.6) and not having the app crash with YouTube (especially since we have weekly challenges) is more important than having the UX a bit better on signup. If we want to improve the signup and payment it will have to be done in a way that a) doesn't break Unity, b) doesn't break the YouTube plugin.

The YouTube issues have been known for long, and I've been saying the plugin is crap. I also admit the 5.6 update could have gone smoother. But that's just how things seem to be with Unity: some things break along the way, and if you want to keep pushing releases out, stuff like this will happen.

I think next time we update Unity, we'll just have to plan the timeline with all teams, and have some sort of feature freeze. Don't know yet how it would be done best, but seems like none of the ways we've done it before has ever worked out well...

**Pull request closed without merging**
